/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    tags: Tag;
    'age-groups': AgeGroup;
    sizes: Size;
    'size-guides': SizeGuide;
    orders: Order;
    couriers: Courier;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'size-guides': SizeGuidesSelect<false> | SizeGuidesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    couriers: CouriersSelect<false> | CouriersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Used in /shop/slug URLs
   */
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kids-wear catalog. Existing products stay valid — new merchandising fields are optional.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  description: string;
  details?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  category: number | Category;
  gender: 'boys' | 'girls' | 'unisex';
  ageGroup: number | AgeGroup;
  /**
   * e.g. 100% cotton jersey, lawn with lining
   */
  material?: string | null;
  /**
   * e.g. Machine wash cold. Do not bleach. Dry in shade.
   */
  careInstructions?: string | null;
  /**
   * Configurable in Admin → Tags
   */
  tags?: (number | Tag)[] | null;
  /**
   * Configurable in Admin → Size guides
   */
  sizeGuide?: (number | null) | SizeGuide;
  featured?: boolean | null;
  /**
   * Higher numbers appear first in the shop. 0 is fine for most products.
   */
  sortPriority?: number | null;
  /**
   * Shown at the bottom of the product page
   */
  relatedProducts?: (number | Product)[] | null;
  seo?: {
    /**
     * Defaults to the product title
     */
    title?: string | null;
    /**
     * Defaults to the short product description
     */
    description?: string | null;
  };
  variants: {
    sku: string;
    size: string;
    color: string;
    /**
     * Price in PKR
     */
    price: number;
    /**
     * Optional original price for sale badge
     */
    compareAtPrice?: number | null;
    stock: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reusable product tags such as Cotton, Eid, or Newborn essentials.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Measurement charts you can attach to products. Newborn and kids usually need different guides.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "size-guides".
 */
export interface AgeGroup {
  id: number
  name: string
  slug: string
  blurb?: string | null
  storefrontVisible?: boolean | null
  sortOrder?: number | null
  heightMinCm: number
  heightMaxCm: number
  ageMinMonths?: number | null
  ageMaxMonths?: number | null
  updatedAt: string
  createdAt: string
}

export interface Size {
  id: number
  code: string
  label: string
  ageLabel?: string | null
  storefrontVisible?: boolean | null
  sortOrder?: number | null
  heightMinCm: number
  heightMaxCm: number
  chestMinCm?: number | null
  chestMaxCm?: number | null
  waistMinCm?: number | null
  waistMaxCm?: number | null
  ageMinMonths?: number | null
  ageMaxMonths?: number | null
  eu?: string | null
  uk?: string | null
  us?: string | null
  ageGroups?: (number | AgeGroup)[] | null
  updatedAt: string
  createdAt: string
}

export interface SizeGuide {
  id: number;
  title: string;
  slug: string;
  /**
   * Short note shown above the chart, e.g. how to measure chest
   */
  description?: string | null;
  measurements?:
    | {
        size: string;
        /**
         * e.g. 3–4 years
         */
        age?: string | null;
        /**
         * e.g. 56 cm
         */
        chest?: string | null;
        length?: string | null;
        waist?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Fit notes: relaxed, true to size, order up if between sizes
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * COD workflow: Pending → Confirmed → Packed → Shipped → Out for delivery → Delivered. Use Cancelled, Refused at door, Failed delivery, or Returned when the parcel does not complete. Mark cash collected when the rider is paid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  /**
   * Happy path: Pending → Confirmed → Packed → Shipped → Out for delivery → Delivered. Exceptions: Cancelled, Refused at door, Failed delivery, Returned.
   */
  status:
    | 'pending'
    | 'confirmed'
    | 'packed'
    | 'shipped'
    | 'out_for_delivery'
    | 'delivered'
    | 'cancelled'
    | 'refused'
    | 'failed_delivery'
    | 'returned';
  paymentMethod: 'cod';
  /**
   * Set Collected when the rider receives cash. Delivered orders that are still unpaid are marked collected automatically.
   */
  paymentStatus: 'unpaid' | 'collected' | 'refunded';
  /**
   * Required context for cancelled, refused, failed, or returned orders. Saved into status history.
   */
  statusReason?: string | null;
  /**
   * Timestamped log of status and payment changes. Staff cannot edit this list.
   */
  statusHistory?:
    | {
        status?:
          | (
              | 'pending'
              | 'confirmed'
              | 'packed'
              | 'shipped'
              | 'out_for_delivery'
              | 'delivered'
              | 'cancelled'
              | 'refused'
              | 'failed_delivery'
              | 'returned'
            )
          | null;
        paymentStatus?: ('unpaid' | 'collected' | 'refunded') | null;
        at?: string | null;
        source?: ('checkout' | 'admin' | 'system') | null;
        actor?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes — not shown to the customer
   */
  adminNotes?: string | null;
  customerName: string;
  phone: string;
  email?: string | null;
  city:
    | 'Karachi'
    | 'Lahore'
    | 'Islamabad'
    | 'Rawalpindi'
    | 'Faisalabad'
    | 'Multan'
    | 'Peshawar'
    | 'Quetta'
    | 'Sialkot'
    | 'Gujranwala'
    | 'Hyderabad'
    | 'Bahawalpur'
    | 'Sargodha'
    | 'Gujrat'
    | 'Sahiwal'
    | 'Abbottabad'
    | 'Rahim Yar Khan'
    | 'Sukkur'
    | 'Larkana'
    | 'Mardan'
    | 'Okara'
    | 'Sheikhupura'
    | 'Jhelum'
    | 'Dera Ghazi Khan'
    | 'Wah Cantt'
    | 'Mirpur'
    | 'Other';
  area: string;
  address: string;
  landmark?: string | null;
  customerNotes?: string | null;
  items: {
    product?: (number | null) | Product;
    title: string;
    sku: string;
    size: string;
    color: string;
    qty: number;
    price: number;
    id?: string | null;
  }[];
  subtotal: number;
  shipping: number;
  codFee: number;
  total: number;
  shipment?: {
    /**
     * Configurable in Admin → Couriers
     */
    courier?: (number | null) | Courier;
    /**
     * Filled from the courier record; you can override
     */
    courierName?: string | null;
    /**
     * Adapter id (manual until a courier API is connected)
     */
    provider?: string | null;
    trackingNumber?: string | null;
    /**
     * Built from the courier tracking URL template when possible
     */
    trackingUrl?: string | null;
    /**
     * Courier consignment id for a future API sync
     */
    externalId?: string | null;
    /**
     * Courier-facing status. Separate from the order fulfillment status.
     */
    shippingStatus?:
      | (
          | 'not_booked'
          | 'booked'
          | 'picked_up'
          | 'in_transit'
          | 'out_for_delivery'
          | 'delivered'
          | 'failed'
          | 'returned'
          | 'cancelled'
        )
      | null;
    shipmentDate?: string | null;
    deliveryDate?: string | null;
    /**
     * Cash the rider should collect, in PKR. Defaults to the order total.
     */
    codAmount?: number | null;
    /**
     * Pickup instructions, bag count, or courier portal notes
     */
    notes?: string | null;
    lastSyncedAt?: string | null;
    lastSyncError?: string | null;
  };
  /**
   * Customer WhatsApp click-to-chat confirmation link
   */
  whatsappConfirmUrl?: string | null;
  /**
   * Outbound notification attempts after the order was placed
   */
  notifications?:
    | {
        channel?: ('whatsapp' | 'email' | 'sms') | null;
        audience?: ('customer' | 'staff') | null;
        status?: ('ready' | 'skipped' | 'sent' | 'failed') | null;
        provider?: string | null;
        to?: string | null;
        error?: string | null;
        at?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Courier names used on orders. Provider stays Manual until a courier API adapter is connected in code — Orders do not need to change.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "couriers".
 */
export interface Courier {
  id: number;
  /**
   * Shown on the order and to the customer (e.g. TCS, Leopards, Shop rider)
   */
  name: string;
  /**
   * Stable id, e.g. tcs or leopard
   */
  slug: string;
  /**
   * Which future API adapter to use. Keep Manual until credentials and an adapter exist.
   */
  provider: 'manual' | 'tcs' | 'leopard' | 'trax' | 'postex' | 'callcourier' | 'rider' | 'other';
  /**
   * Optional public tracking page. Use {trackingNumber} or {cn}, e.g. https://example.com/track/{trackingNumber}
   */
  trackingUrlTemplate?: string | null;
  active?: boolean | null;
  /**
   * Internal — pickup account, city coverage, etc.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'size-guides';
        value: number | SizeGuide;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'couriers';
        value: number | Courier;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  details?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  gender?: T;
  ageGroup?: T;
  material?: T;
  careInstructions?: T;
  tags?: T;
  sizeGuide?: T;
  featured?: T;
  sortPriority?: T;
  relatedProducts?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  variants?:
    | T
    | {
        sku?: T;
        size?: T;
        color?: T;
        price?: T;
        compareAtPrice?: T;
        stock?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "size-guides_select".
 */
export interface SizeGuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  measurements?:
    | T
    | {
        size?: T;
        age?: T;
        chest?: T;
        length?: T;
        waist?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  statusReason?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        paymentStatus?: T;
        at?: T;
        source?: T;
        actor?: T;
        note?: T;
        id?: T;
      };
  adminNotes?: T;
  customerName?: T;
  phone?: T;
  email?: T;
  city?: T;
  area?: T;
  address?: T;
  landmark?: T;
  customerNotes?: T;
  items?:
    | T
    | {
        product?: T;
        title?: T;
        sku?: T;
        size?: T;
        color?: T;
        qty?: T;
        price?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  codFee?: T;
  total?: T;
  shipment?:
    | T
    | {
        courier?: T;
        courierName?: T;
        provider?: T;
        trackingNumber?: T;
        trackingUrl?: T;
        externalId?: T;
        shippingStatus?: T;
        shipmentDate?: T;
        deliveryDate?: T;
        codAmount?: T;
        notes?: T;
        lastSyncedAt?: T;
        lastSyncError?: T;
      };
  whatsappConfirmUrl?: T;
  notifications?:
    | T
    | {
        channel?: T;
        audience?: T;
        status?: T;
        provider?: T;
        to?: T;
        error?: T;
        at?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "couriers_select".
 */
export interface CouriersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  provider?: T;
  trackingUrlTemplate?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  storeName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  announcement?: string | null;
  /**
   * Used for order WhatsApp buttons (03XXXXXXXXX)
   */
  whatsapp: string;
  phone?: string | null;
  email?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  /**
   * Free delivery when subtotal reaches this PKR amount
   */
  freeShippingThreshold?: number | null;
  /**
   * Fallback shipping fee in PKR
   */
  defaultShippingFee?: number | null;
  /**
   * Optional cash-on-delivery handling fee
   */
  codFee?: number | null;
  cityShipping?:
    | {
        city:
          | 'Karachi'
          | 'Lahore'
          | 'Islamabad'
          | 'Rawalpindi'
          | 'Faisalabad'
          | 'Multan'
          | 'Peshawar'
          | 'Quetta'
          | 'Sialkot'
          | 'Gujranwala'
          | 'Hyderabad'
          | 'Bahawalpur'
          | 'Sargodha'
          | 'Gujrat'
          | 'Sahiwal'
          | 'Abbottabad'
          | 'Rahim Yar Khan'
          | 'Sukkur'
          | 'Larkana'
          | 'Mardan'
          | 'Okara'
          | 'Sheikhupura'
          | 'Jhelum'
          | 'Dera Ghazi Khan'
          | 'Wah Cantt'
          | 'Mirpur'
          | 'Other';
        fee: number;
        id?: string | null;
      }[]
    | null;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  heroCta?: string | null;
  /**
   * Storefront path, e.g. /shop or /shop/girls
   */
  heroCtaLink?: string | null;
  heroSecondaryCta?: string | null;
  heroSecondaryCtaLink?: string | null;
  /**
   * Shown when there is no hero image
   */
  heroOverlayTitle?: string | null;
  heroOverlaySubtitle?: string | null;
  /**
   * Leave empty to hide the banner
   */
  homeBannerTitle?: string | null;
  homeBannerCopy?: string | null;
  homeBannerCta?: string | null;
  homeBannerCtaLink?: string | null;
  /**
   * Empty uses Boys / Girls / Newborn. Fill this to replace those cards.
   */
  homeCollections?:
    | {
        title: string;
        copy?: string | null;
        /**
         * Optional. Links to /shop/{slug} unless you set a custom path.
         */
        category?: (number | null) | Category;
        /**
         * Optional custom path, e.g. /shop/boys
         */
        href?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  featuredEyebrow?: string | null;
  featuredHeading?: string | null;
  featuredCta?: string | null;
  featuredCtaLink?: string | null;
  featuredEmptyMessage?: string | null;
  /**
   * Optional. Empty shows products marked Featured, then newest published items.
   */
  homeFeaturedProducts?: (number | Product)[] | null;
  /**
   * Empty keeps Cash on delivery / Pakistan-wide / Easy exchanges.
   */
  homePromos?:
    | {
        icon?: ('cod' | 'shipping' | 'returns' | 'sparkles') | null;
        title: string;
        copy: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to hide this block
   */
  homeStoryTitle?: string | null;
  homeStoryEyebrow?: string | null;
  homeStoryBody?: string | null;
  homeStoryImage?: (number | null) | Media;
  homeStoryCta?: string | null;
  homeStoryCtaLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  storeName?: T;
  tagline?: T;
  logo?: T;
  announcement?: T;
  whatsapp?: T;
  phone?: T;
  email?: T;
  instagram?: T;
  facebook?: T;
  freeShippingThreshold?: T;
  defaultShippingFee?: T;
  codFee?: T;
  cityShipping?:
    | T
    | {
        city?: T;
        fee?: T;
        id?: T;
      };
  heroEyebrow?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroCta?: T;
  heroCtaLink?: T;
  heroSecondaryCta?: T;
  heroSecondaryCtaLink?: T;
  heroOverlayTitle?: T;
  heroOverlaySubtitle?: T;
  homeBannerTitle?: T;
  homeBannerCopy?: T;
  homeBannerCta?: T;
  homeBannerCtaLink?: T;
  homeCollections?:
    | T
    | {
        title?: T;
        copy?: T;
        category?: T;
        href?: T;
        image?: T;
        id?: T;
      };
  featuredEyebrow?: T;
  featuredHeading?: T;
  featuredCta?: T;
  featuredCtaLink?: T;
  featuredEmptyMessage?: T;
  homeFeaturedProducts?: T;
  homePromos?:
    | T
    | {
        icon?: T;
        title?: T;
        copy?: T;
        id?: T;
      };
  homeStoryTitle?: T;
  homeStoryEyebrow?: T;
  homeStoryBody?: T;
  homeStoryImage?: T;
  homeStoryCta?: T;
  homeStoryCtaLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}