/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    orders: Order;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Used in /shop/slug URLs
   */
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  description: string;
  details?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  category: number | Category;
  gender: 'boys' | 'girls' | 'unisex';
  ageGroup: 'newborn' | 'infant' | 'toddler' | 'kids';
  featured?: boolean | null;
  variants: {
    sku: string;
    size:
      | 'newborn'
      | '0-3m'
      | '3-6m'
      | '6-9m'
      | '9-12m'
      | '12-18m'
      | '18-24m'
      | '2y'
      | '3y'
      | '4y'
      | '5y'
      | '6y'
      | '7-8y'
      | '9-10y'
      | '11-12y';
    color: string;
    /**
     * Price in PKR
     */
    price: number;
    /**
     * Optional original price for sale badge
     */
    compareAtPrice?: number | null;
    stock: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * COD workflow: Pending → Confirmed → Packed → Shipped → Out for delivery → Delivered. Use Cancelled, Refused at door, Failed delivery, or Returned when the parcel does not complete. Mark cash collected when the rider is paid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  /**
   * Happy path: Pending → Confirmed → Packed → Shipped → Out for delivery → Delivered. Exceptions: Cancelled, Refused at door, Failed delivery, Returned.
   */
  status:
    | 'pending'
    | 'confirmed'
    | 'packed'
    | 'shipped'
    | 'out_for_delivery'
    | 'delivered'
    | 'cancelled'
    | 'refused'
    | 'failed_delivery'
    | 'returned';
  paymentMethod: 'cod';
  /**
   * Set Collected when the rider receives cash. Delivered orders that are still unpaid are marked collected automatically.
   */
  paymentStatus: 'unpaid' | 'collected' | 'refunded';
  /**
   * Required context for cancelled, refused, failed, or returned orders. Saved into status history.
   */
  statusReason?: string | null;
  /**
   * Timestamped log of status and payment changes. Staff cannot edit this list.
   */
  statusHistory?:
    | {
        status?:
          | (
              | 'pending'
              | 'confirmed'
              | 'packed'
              | 'shipped'
              | 'out_for_delivery'
              | 'delivered'
              | 'cancelled'
              | 'refused'
              | 'failed_delivery'
              | 'returned'
            )
          | null;
        paymentStatus?: ('unpaid' | 'collected' | 'refunded') | null;
        at?: string | null;
        source?: ('checkout' | 'admin' | 'system') | null;
        actor?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes — not shown to the customer
   */
  adminNotes?: string | null;
  customerName: string;
  phone: string;
  email?: string | null;
  city:
    | 'Karachi'
    | 'Lahore'
    | 'Islamabad'
    | 'Rawalpindi'
    | 'Faisalabad'
    | 'Multan'
    | 'Peshawar'
    | 'Quetta'
    | 'Sialkot'
    | 'Gujranwala'
    | 'Hyderabad'
    | 'Bahawalpur'
    | 'Sargodha'
    | 'Gujrat'
    | 'Sahiwal'
    | 'Abbottabad'
    | 'Rahim Yar Khan'
    | 'Sukkur'
    | 'Larkana'
    | 'Mardan'
    | 'Okara'
    | 'Sheikhupura'
    | 'Jhelum'
    | 'Dera Ghazi Khan'
    | 'Wah Cantt'
    | 'Mirpur'
    | 'Other';
  area: string;
  address: string;
  landmark?: string | null;
  customerNotes?: string | null;
  items: {
    product?: (number | null) | Product;
    title: string;
    sku: string;
    size: string;
    color: string;
    qty: number;
    price: number;
    id?: string | null;
  }[];
  subtotal: number;
  shipping: number;
  codFee: number;
  total: number;
  /**
   * Customer WhatsApp click-to-chat confirmation link
   */
  whatsappConfirmUrl?: string | null;
  /**
   * Outbound notification attempts after the order was placed
   */
  notifications?:
    | {
        channel?: ('whatsapp' | 'email' | 'sms') | null;
        audience?: ('customer' | 'staff') | null;
        status?: ('ready' | 'skipped' | 'sent' | 'failed') | null;
        provider?: string | null;
        to?: string | null;
        error?: string | null;
        at?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  details?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  gender?: T;
  ageGroup?: T;
  featured?: T;
  variants?:
    | T
    | {
        sku?: T;
        size?: T;
        color?: T;
        price?: T;
        compareAtPrice?: T;
        stock?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  statusReason?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        paymentStatus?: T;
        at?: T;
        source?: T;
        actor?: T;
        note?: T;
        id?: T;
      };
  adminNotes?: T;
  customerName?: T;
  phone?: T;
  email?: T;
  city?: T;
  area?: T;
  address?: T;
  landmark?: T;
  customerNotes?: T;
  items?:
    | T
    | {
        product?: T;
        title?: T;
        sku?: T;
        size?: T;
        color?: T;
        qty?: T;
        price?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  codFee?: T;
  total?: T;
  whatsappConfirmUrl?: T;
  notifications?:
    | T
    | {
        channel?: T;
        audience?: T;
        status?: T;
        provider?: T;
        to?: T;
        error?: T;
        at?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  storeName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  announcement?: string | null;
  /**
   * Used for order WhatsApp buttons (03XXXXXXXXX)
   */
  whatsapp: string;
  phone?: string | null;
  email?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  /**
   * Free delivery when subtotal reaches this PKR amount
   */
  freeShippingThreshold?: number | null;
  /**
   * Fallback shipping fee in PKR
   */
  defaultShippingFee?: number | null;
  /**
   * Optional cash-on-delivery handling fee
   */
  codFee?: number | null;
  cityShipping?:
    | {
        city:
          | 'Karachi'
          | 'Lahore'
          | 'Islamabad'
          | 'Rawalpindi'
          | 'Faisalabad'
          | 'Multan'
          | 'Peshawar'
          | 'Quetta'
          | 'Sialkot'
          | 'Gujranwala'
          | 'Hyderabad'
          | 'Bahawalpur'
          | 'Sargodha'
          | 'Gujrat'
          | 'Sahiwal'
          | 'Abbottabad'
          | 'Rahim Yar Khan'
          | 'Sukkur'
          | 'Larkana'
          | 'Mardan'
          | 'Okara'
          | 'Sheikhupura'
          | 'Jhelum'
          | 'Dera Ghazi Khan'
          | 'Wah Cantt'
          | 'Mirpur'
          | 'Other';
        fee: number;
        id?: string | null;
      }[]
    | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  heroCta?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  storeName?: T;
  tagline?: T;
  logo?: T;
  announcement?: T;
  whatsapp?: T;
  phone?: T;
  email?: T;
  instagram?: T;
  facebook?: T;
  freeShippingThreshold?: T;
  defaultShippingFee?: T;
  codFee?: T;
  cityShipping?:
    | T
    | {
        city?: T;
        fee?: T;
        id?: T;
      };
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroCta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}